### ISSUE TITLE
Energy boundary definition differs from XSPEC

### ISSUE THREAD

**Issue by dbxifu** [renecotyfanboy/jaxspec#100]
When defining energy boundaries to fit a spectrum, you get one channel more in jaxspec (observation) than in XSPEC.

**Comment by renecotyfanboy** [comment]
From what I checked on my side, I had okay bins when compared to Xspec. However, it might be a bad channel issue which is not accounted for yet (#104). Could you check if there is any bad channel excluded when you run `ignore bad` in your spectrum?
