### ISSUE TITLE
Implement "ig bad"

### ISSUE THREAD

**Issue by ErwanQuintin** [renecotyfanboy/jaxspec#104]
Implement the Xspec "ignore bad" command (Section 8.2.3 of https://heasarc.gsfc.nasa.gov/docs/asca/abc/node9.html) that removes all channels with bad quality flags. 

In practice: remove channels where QUALITY FLAG > 0

**Comment by dbxifu** [comment]
There is indeed one bad channel in my spectrum; this is the first one.
