### ISSUE TITLE
Installing jaxspec on Mac M1 

### ISSUE THREAD

**Issue by CamilleDiez** [renecotyfanboy/jaxspec#131]
At this time installation on mac with Apple silicon is not working with `pip`. There is a workaround which consists in uninstalling jax and jaxlib and reinstalling with `conda` which comes with its own wheels 

```
pip uninstall jax jaxlib
conda install -c conda-forge jaxlib
conda install -c conda-forge jax
```

It just works. LF updates with `jax-metal` to get GPU integration

**Comment by CamilleDiez** [comment]
Code fails when compiled with `jit` and installing jax-metal with `pip` does not work here

**Comment by renecotyfanboy** [comment]
`jaxspec` seems to work properly on Apple Silicon CPU. GPU integration will be bounded to clean `jax-metal` releases
