### ISSUE TITLE
Add guidelines for install of jaxspec (and jaxlib dependency) on hardware without AVX instructions

### ISSUE THREAD

**Issue by sguillot** [renecotyfanboy/jaxspec#171]
which leads to 
```RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support.```

**Comment by renecotyfanboy** [comment]
I found a relevant discussion [here](https://github.com/google/jax/discussions/19343) @sguillot

**Comment by sguillot** [comment]
yes, I saw that page, but I haven't tried it on my Mac.
On a Ubuntu, Pierre had the same problem but managed to install JaxLib from source (but it ended up being a version too recent for JaxSpec)

**Comment by renecotyfanboy** [comment]
I discussed a bit with Lucien and it appears that it was an issue with `bell`. I had a similar issue on some nodes on `titan`, and it was mostly due to too old software, outdated virtualisation and/or outdated hardware products

**Comment by renecotyfanboy** [comment]
Seems to be a niche issue. I'll reopen if necessary
