### ISSUE TITLE
Associate Backfile, RMFfile or ARFfile with a PHA dataset when a path is written in the header

### ISSUE THREAD

**Issue by FlorentXIFU** [renecotyfanboy/jaxspec#30]
DataPHA has backfile, respfile and ancrfile arguments that are path to corresponding background dataset, response file and ancillary file, respectively.

When a DataPHA instance is created, it must be associated with background file and/or DataRMF and/or DataARF class if a path is written in previous arguments.

**Comment by renecotyfanboy** [comment]
Fixed with #45 and #46, now loading a pha using Observation.from_pha will search for arf and rmf, background will be implemented in a near future
