### ISSUE TITLE
Response file could be a rsp file

### ISSUE THREAD

**Issue by FlorentXIFU** [renecotyfanboy/jaxspec#31]
For the moment, respfile argument is for rmf file and ancrfile is for arf file.

It should be taken into account that respfile might be a RSP file (rsp = rmf * arf) and in this case, there is no ancrfile but the instrument response is entirely encoded in the respfile.

**Comment by renecotyfanboy** [comment]
Lies in extension name, could either "MATRIX" or "SPECRESP MATRIX"
